# mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: cm9vdHBhc3M=        # base64 of 'rootpass'
  user-password: cG9ydHBhc3M=        # base64 of 'portpass'
